version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
    - build:
        filters:
          branches:
            only: master

jobs:
  build:
    docker:
    - image: circleci/golang:1.16

    working_directory: /go/src/github.com/JamesClonk/iRvisualizer

    steps:
    - setup_remote_docker:
        docker_layer_caching: true
    - checkout

    # test
    - run: make test

    # build and publish image
    - run: make image-login
    - run: make image-build
    - run: make image-publish

    # # deploy to Swisscom Application Cloud
    # - deploy:
    #     name: appcloud push
    #     command: |
    #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
    #         chmod +x scripts/cf_deploy.sh
    #         scripts/cf_deploy.sh
    #       fi
